# Generated by Django 6.0.6 on 2026-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('placement', models.CharField(choices=[('home_top', 'Home - Top Banner'), ('home_sidebar', 'Home - Sidebar'), ('notes_top', 'Notes - Top'), ('notes_middle', 'Notes - Middle'), ('notes_bottom', 'Notes - Bottom'), ('blog_top', 'Blog - Top'), ('blog_middle', 'Blog - Middle (after content)'), ('blog_sidebar', 'Blog - Sidebar'), ('quiz_result', 'Quiz Result Page'), ('downloads_top', 'Downloads - Top'), ('sidebar', 'Global Sidebar'), ('footer', 'Global Footer')], max_length=50, unique=True)),
                ('ad_code', models.TextField(help_text='AdSense or HTML ad code')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-book', max_length=100)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('notes', 'Notes'), ('downloads', 'Downloads'), ('blog', 'Blog'), ('quiz', 'Quiz')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Learning Platform', max_length=200)),
                ('site_tagline', models.CharField(default='Your Gateway to Knowledge', max_length=300)),
                ('site_description', models.TextField(default='An educational platform for students')),
                ('owner_name', models.CharField(default='Admin', max_length=200)),
                ('owner_bio', models.TextField(default='')),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission', models.TextField(default='')),
                ('vision', models.TextField(default='')),
                ('contact_email', models.EmailField(default='admin@learningplatform.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('adsense_client_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
