# Generated by Django 5.0.6 on 2026-06-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_site_favicon_sitesettings_site_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_favicon',
            new_name='site_favico',
        ),
    ]
