# Generated by Django 5.0.6 on 2026-06-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_site_favicon_sitesettings_site_favico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_favico',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
    ]
