# Generated by Django 5.0.6 on 2026-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_site_favico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
