# Generated by Django 5.0.6 on 2026-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visitorcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='ad_image',
            field=models.ImageField(blank=True, help_text='Upload an ad image (PNG, JPG). Used for popup or banner ads.', null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='link_url',
            field=models.URLField(blank=True, default='', help_text='URL to open when the ad image is clicked'),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='ad_code',
            field=models.TextField(blank=True, default='', help_text='AdSense or HTML ad code'),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='placement',
            field=models.CharField(choices=[('home_top', 'Home - Top Banner'), ('home_sidebar', 'Home - Sidebar'), ('notes_top', 'Notes - Top'), ('notes_middle', 'Notes - Middle'), ('notes_bottom', 'Notes - Bottom'), ('blog_top', 'Blog - Top'), ('blog_middle', 'Blog - Middle (after content)'), ('blog_sidebar', 'Blog - Sidebar'), ('quiz_result', 'Quiz Result Page'), ('downloads_top', 'Downloads - Top'), ('sidebar', 'Global Sidebar'), ('footer', 'Global Footer'), ('popup', 'Popup - Full Screen Overlay')], max_length=50, unique=True),
        ),
    ]
