# Generated by Django 6.0.7 on 2026-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adplacement_ad_image_adplacement_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_push_on_blog',
            field=models.BooleanField(default=True, help_text='Automatically broadcast push notification when a new blog post is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_push_on_quiz',
            field=models.BooleanField(default=True, help_text='Automatically broadcast push notification when a new quiz is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_web_push',
            field=models.BooleanField(default=False, help_text='Master switch to enable or disable browser push notifications for visitors'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='onesignal_app_id',
            field=models.CharField(blank=True, default='', help_text='OneSignal App ID (from your free OneSignal dashboard at onesignal.com)', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='onesignal_rest_api_key',
            field=models.CharField(blank=True, default='', help_text='OneSignal REST API Key for automated backend push broadcasts', max_length=150),
        ),
    ]
