# Generated by Django 6.0.7 on 2026-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_auto_push_on_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='owner_experience',
            field=models.CharField(blank=True, default='7+ Years IT & Loksewa Experience', help_text='Highlights such as years of experience or credentials', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_tagline',
            field=models.CharField(blank=True, default='Loksewa & Tech Preparation Specialist', help_text='A short tagline or headline displayed with your profile', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_title',
            field=models.CharField(blank=True, default='Educator & Mentor', help_text='Your professional title or role (e.g. Educator & Mentor, Computer Operator Trainer, Teacher, IT Officer)', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(default='Tulasi Nepali', max_length=200),
        ),
    ]
