# Generated by Django 6.0.7 on 2026-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_owner_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_experience',
            field=models.CharField(blank=True, default='IT Specialist & Educator', help_text='Highlights such as years of experience or credentials', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_tagline',
            field=models.CharField(blank=True, default='Technology, GK & Competitive Learning Mentor', help_text='A short tagline or headline displayed with your profile', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='An open educational platform for technology, computing, general knowledge, and competitive exam preparation.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Learn Technology, General Knowledge & Exam Preparation', max_length=300),
        ),
    ]
