# Generated by Django 6.0.7 on 2026-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesettings_owner_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='homepage_newsletter', max_length=100)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_email_on_blog',
            field=models.BooleanField(default=False, help_text='Automatically email subscribers when a new Blog article is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_email_on_download',
            field=models.BooleanField(default=False, help_text='Automatically email subscribers when a new Download file is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_email_on_note',
            field=models.BooleanField(default=False, help_text='Automatically email subscribers when a new Study Note is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_email_on_quiz',
            field=models.BooleanField(default=False, help_text='Automatically email subscribers when a new Quiz is published'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='SMTP Host, e.g. smtp.gmail.com or smtp.zoho.com', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='SMTP Password or App Password', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, default='', help_text='SMTP Username / Email address', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, default=587, help_text='SMTP Port (usually 587 for TLS or 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption (recommended for port 587)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sender_email',
            field=models.EmailField(blank=True, default='', help_text='The "From" email address displayed to subscribers (leave blank to use contact email)', max_length=254),
        ),
    ]
