# Generated by Django 6.0.5 on 2026-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ads_txt_content',
            field=models.TextField(blank=True, default='google.com, pub-3956705237421931, DIRECT, f08c47fec0942fa0', help_text='Content for /ads.txt file (Google AdSense and authorized digital sellers)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_verification_method',
            field=models.CharField(choices=[('code', 'AdSense code snippet'), ('adstxt', 'Ads.txt snippet'), ('meta', 'Meta tag')], default='code', help_text='AdSense verification method for your site', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adsense_client_id',
            field=models.CharField(blank=True, default='ca-pub-3956705237421931', help_text='Google AdSense Publisher ID (e.g. ca-pub-3956705237421931)', max_length=100),
        ),
    ]
