# Generated by Django 6.0.5 on 2026-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_ads_txt_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_code_snippet',
            field=models.TextField(blank=True, default='<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3956705237421931" crossorigin="anonymous"></script>', help_text='AdSense code snippet inserted between <head> tags'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_meta_tag',
            field=models.TextField(blank=True, default='<meta name="google-adsense-account" content="ca-pub-3956705237421931">', help_text='AdSense verification meta tag inserted between <head> tags'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ads_txt',
            field=models.BooleanField(default=True, help_text='Enable serving ads.txt file'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_adsense_code',
            field=models.BooleanField(default=True, help_text='Automatically add AdSense code snippet to <head> on all pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_adsense_meta',
            field=models.BooleanField(default=True, help_text='Automatically add AdSense meta tag to <head> on all pages'),
        ),
    ]
