# Generated by Django 6.0.5 on 2026-10-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
        ('core', '0015_sitesettings_adsense_code_snippet_and_more'),
        ('notes', '0002_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=350)),
                ('content_type', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('article_url', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_blog_publish_mode',
            field=models.CharField(choices=[('published', 'Publish Immediately (Live)'), ('draft', 'Save as Draft (Require Review)')], default='published', help_text='Publication status for auto-generated blogs', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_default_blog_category',
            field=models.ForeignKey(blank=True, help_text='Default category for auto-generated blogs if none specified', limit_choices_to={'module': 'blog'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_ai_blogs', to='core.category'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_default_language',
            field=models.CharField(choices=[('bilingual', 'Bilingual (नेपाली with English terms - Recommended)'), ('ne', 'Pure Nepali (नेपाली - देवनागरी)'), ('en', 'English')], default='bilingual', help_text='Default language for generated articles', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_default_note_category',
            field=models.ForeignKey(blank=True, help_text='Default category for auto-generated notes if none specified', limit_choices_to={'module': 'notes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_ai_notes', to='core.category'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_note_publish_mode',
            field=models.CharField(choices=[('published', 'Publish Immediately (Live)'), ('draft', 'Save as Draft (Require Review)')], default='published', help_text='Publication status for auto-generated notes', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_daily_ai_blog',
            field=models.BooleanField(default=False, help_text='Enable daily automated generation of 1 blog post'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_daily_ai_note',
            field=models.BooleanField(default=False, help_text='Enable daily automated generation of 1 study note'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Gemini API Key from Google AI Studio (aistudio.google.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash (Fastest & Free Tier)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Reliable & Free Tier)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Deep & Comprehensive)')], default='gemini-2.0-flash', help_text='Gemini AI model engine for article generation', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_ai_blog_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_ai_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AITopicQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Topic title or prompt idea', max_length=350)),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post (लेख / ब्लग)'), ('note', 'Study Note (अध्ययन सामग्री / नोट)')], default='blog', max_length=20)),
                ('language', models.CharField(choices=[('bilingual', 'Bilingual (नेपाली + English)'), ('ne', 'Nepali (नेपाली - देवनागरी)'), ('en', 'English')], default='bilingual', max_length=20)),
                ('prompt_hint', models.TextField(blank=True, help_text='Optional custom instructions, target audience, or specific subtopics to cover')),
                ('status', models.CharField(choices=[('pending', 'Pending Queue'), ('generating', 'Generating...'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = higher priority')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Target category (optional, will fallback to default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_topics', to='core.category')),
                ('generated_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_source_topics', to='blog.blogpost')),
                ('generated_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_source_topics', to='notes.note')),
            ],
            options={
                'verbose_name': 'AI Topic Queue',
                'verbose_name_plural': 'AI Topic Queue',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
