# Generated by Django 5.0.6 on 2026-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.BooleanField(default=False, help_text='Enable negative marking for wrong answers'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marking_value',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Marks deducted per wrong answer (e.g., 0.25 means 0.25 marks deducted). Only applies if negative marking is enabled.', max_digits=3),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of correctly answered questions'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='final_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final score after negative marking (correct - negative_marks)', max_digits=6),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='incorrect_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of wrongly answered questions'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total marks deducted due to negative marking', max_digits=6),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='unanswered_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of unanswered questions'),
        ),
    ]
