# Generated by Django 5.0.6 on 2026-06-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_negative_marking_quiz_negative_marking_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative_marking_value',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Percentage of marks deducted per wrong answer (e.g., 20 means 20%% deducted). Only applies if negative marking is enabled.', max_digits=5),
        ),
    ]
