# Generated by Django 6.0.7 on 2026-10-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_negative_marking_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Student / Visitor', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1 to 5 stars')),
                ('feedback_type', models.CharField(choices=[('general', 'General Review & Rating'), ('question_error', 'Question Error / Typo Report'), ('suggestion', 'Content Suggestion'), ('difficulty', 'Difficulty Feedback')], default='general', max_length=20)),
                ('message', models.TextField(help_text='Feedback thoughts, review, or issue description')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, help_text='Specific question reported, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Feedback',
                'verbose_name_plural': 'Quiz Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
