# Generated by Django 6.0.6 on 2026-06-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('summary', models.TextField(help_text='Brief summary for SEO', max_length=500)),
                ('file', models.FileField(upload_to='downloads/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('zip', 'ZIP'), ('other', 'Other')], max_length=10)),
                ('file_size', models.CharField(blank=True, help_text='e.g. 2.5 MB', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='downloads/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'module': 'downloads'}, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='downloads', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
