# Generated by Django 6.0.7 on 2026-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('zip', 'ZIP'), ('other', 'Other')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='download',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
