# Generated by Django 6.0.6 on 2026-06-05 13:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('summary', models.TextField(help_text='Brief summary for SEO and cards', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'module': 'notes'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
