# Generated by Django 6.0.7 on 2026-09-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon', models.CharField(default='bi-tools', help_text='Bootstrap Icon class (e.g., bi-calendar3, bi-calculator)', max_length=50)),
                ('category', models.CharField(choices=[('converter', 'Date & Units Converter'), ('calculator', 'Calculators'), ('typing', 'Typing & Font Utilities'), ('general', 'General Utilities')], default='converter', max_length=30)),
                ('short_description', models.TextField(help_text='Brief explanation of what the tool does')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this tool across the platform')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort display order (lowest first)')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_embedding', models.BooleanField(default=True, help_text='Global toggle: allow other websites to embed widgets via iframe')),
                ('branding_text', models.CharField(default='Powered by Tulasi Nepali', max_length=100)),
                ('branding_url', models.URLField(default='https://tulasinepali.com.np')),
                ('show_ads_in_widgets', models.BooleanField(default=False, help_text='Render AdSense banner inside embedded widget iframes')),
            ],
            options={
                'verbose_name': 'Widget Global Setting',
                'verbose_name_plural': 'Widget Global Settings',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon', models.CharField(default='bi-puzzle', help_text='Bootstrap icon', max_length=50)),
                ('badge_text', models.CharField(blank=True, default='Free Widget', max_length=50)),
                ('short_description', models.TextField(help_text='Why external webmasters/bloggers should embed this widget')),
                ('default_width', models.CharField(default='100%', max_length=20)),
                ('default_height', models.CharField(default='480', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active widgets appear on the /widgets/ showcase page')),
                ('order', models.PositiveIntegerField(default=0)),
                ('embed_count', models.PositiveIntegerField(default=0, help_text='Count of times embed code has been generated')),
                ('custom_html', models.TextField(blank=True, help_text='Optional custom iframe/HTML template code for custom widgets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Embeddable Widget',
                'verbose_name_plural': 'Embeddable Widgets',
                'ordering': ['order', 'title'],
            },
        ),
    ]
