# Generated by Django 6.0.7 on 2026-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_seed_nepali_patro_tool_and_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_bs', models.PositiveSmallIntegerField(default=2083, help_text='Bikram Sambat Year (e.g. 2083, 2084)')),
                ('month_bs', models.PositiveSmallIntegerField(choices=[(1, '१. बैशाख (Baisakh)'), (2, '२. जेठ (Jestha)'), (3, '३. असार (Ashadh)'), (4, '४. साउन (Shrawan)'), (5, '५. भदौ (Bhadra)'), (6, '६. असोज (Ashwin)'), (7, '७. कात्तिक (Kartik)'), (8, '८. मंसिर (Mangsir)'), (9, '९. पुस (Poush)'), (10, '१०. माघ (Magh)'), (11, '११. फागुन (Falgun)'), (12, '१२. चैत (Chaitra)')], default=1, help_text='B.S. Month (1 to 12)')),
                ('day_bs', models.PositiveSmallIntegerField(help_text='B.S. Day (1 to 32)')),
                ('title', models.CharField(help_text='Event or holiday name in Nepali (e.g. नयाँ वर्ष, विजया दशमी)', max_length=200)),
                ('title_en', models.CharField(blank=True, help_text='Optional English title', max_length=200)),
                ('is_public_holiday', models.BooleanField(default=True, help_text='Check to highlight as official public holiday in red')),
                ('event_type', models.CharField(choices=[('holiday', 'सार्वजनिक बिदा (Public Holiday)'), ('festival', 'चाडपर्व / उत्सव (Festival)'), ('national', 'राष्ट्रिय दिवस (National Day)'), ('international', 'अन्तर्राष्ट्रिय दिवस (International Day)'), ('exam', 'परीक्षा / शैक्षिक सूचना (Educational)')], default='holiday', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Optional additional notes or gazette notice reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patro Event / Holiday',
                'verbose_name_plural': 'Patro Events / Holidays',
                'ordering': ['year_bs', 'month_bs', 'day_bs'],
                'unique_together': {('year_bs', 'month_bs', 'day_bs', 'title')},
            },
        ),
    ]
