# Generated by Django 6.0.7 on 2026-09-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_seed_initial_patro_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Hostname or domain embedding this widget', max_length=255)),
                ('full_url', models.URLField(blank=True, help_text='Full referrer URL if provided', max_length=500)),
                ('total_views', models.PositiveIntegerField(default=1, help_text='Total embed views from this domain')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal preview on our own domain / localhost')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='tools.widget')),
            ],
            options={
                'verbose_name': 'Widget Usage / Domain',
                'verbose_name_plural': 'Widget Usages / Domains',
                'ordering': ['-total_views', '-last_seen'],
                'unique_together': {('widget', 'domain')},
            },
        ),
    ]
